version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ceos-belin-eft
    command: /sbin/init
    hostname: ceos
    stdin_open: true
    tty: true
    privileged: true
    env_file:
      - ./ceos.env
